# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

CRATES="
	ahash@0.8.11
	aho-corasick@1.1.3
	ansi_term@0.12.1
	anstream@0.6.15
	anstyle-parse@0.2.5
	anstyle-query@1.1.1
	anstyle-wincon@3.0.4
	anstyle@1.0.8
	autocfg@1.3.0
	bitflags@1.3.2
	bitflags@2.6.0
	byteorder@1.5.0
	castaway@0.2.3
	cfg-if@1.0.0
	clap@4.5.11
	clap_builder@4.5.11
	clap_derive@4.5.11
	clap_lex@0.7.2
	colorchoice@1.0.2
	compact_str@0.8.1
	crossbeam-channel@0.5.15
	crossbeam-utils@0.8.20
	crossterm@0.28.1
	crossterm_winapi@0.9.1
	csv-core@0.1.11
	csv@1.3.0
	cursive-macros@0.1.0
	cursive@0.21.1
	cursive_core@0.4.6
	darling@0.20.10
	darling_core@0.20.10
	darling_macro@0.20.10
	deranged@0.3.11
	enum-map-derive@0.17.0
	enum-map@2.7.3
	enumset@1.1.5
	enumset_derive@0.10.0
	errno@0.3.10
	fnv@1.0.7
	getrandom@0.2.15
	glob@0.3.1
	heck@0.5.0
	ident_case@1.0.1
	include_dir@0.7.4
	include_dir_macros@0.7.4
	is_terminal_polyfill@1.70.1
	itoa@1.0.11
	lazy_static@1.5.0
	libc@0.2.169
	libudev-sys@0.1.4
	linux-raw-sys@0.4.14
	lock_api@0.4.12
	log@0.4.22
	memchr@2.7.4
	memoffset@0.7.1
	mio@1.0.3
	nix@0.26.4
	num-complex@0.4.6
	num-conv@0.1.0
	num-integer@0.1.46
	num-iter@0.1.45
	num-rational@0.4.2
	num-traits@0.2.19
	num@0.4.3
	num_threads@0.1.7
	once_cell@1.19.0
	parking_lot@0.12.3
	parking_lot_core@0.9.10
	pin-utils@0.1.0
	pkg-config@0.3.30
	powerfmt@0.2.0
	ppv-lite86@0.2.19
	proc-macro2@1.0.86
	quote@1.0.36
	rand@0.8.5
	rand_chacha@0.3.1
	rand_core@0.6.4
	redox_syscall@0.5.3
	regex-automata@0.4.7
	regex-syntax@0.8.4
	regex@1.10.5
	rustix@0.38.42
	rustversion@1.0.17
	ryu@1.0.18
	scopeguard@1.2.0
	serde@1.0.204
	serde_derive@1.0.204
	serde_json@1.0.121
	signal-hook-mio@0.2.4
	signal-hook-registry@1.4.2
	signal-hook@0.3.17
	smallvec@1.13.2
	static_assertions@1.1.0
	strsim@0.11.1
	syn@2.0.72
	time-core@0.1.2
	time-macros@0.2.18
	time@0.3.36
	udev@0.7.0
	unicode-ident@1.0.12
	unicode-segmentation@1.11.0
	unicode-width@0.1.13
	utf8parse@0.2.2
	uuid@1.10.0
	version_check@0.9.5
	wasi@0.11.0+wasi-snapshot-preview1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.52.0
	windows-targets@0.52.6
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.52.6
	xi-unicode@0.3.0
	zerocopy-derive@0.7.35
	zerocopy@0.7.35
"

inherit cargo

DESCRIPTION="Thunderbolt/USB4 debugging tools"
HOMEPAGE="https://github.com/intel/tbtools"
SRC_URI="
        https://github.com/intel/${PN}/archive/refs/tags/v${PV}.tar.gz -> ${P}.gh.tar.gz
        ${CARGO_CRATE_URIS}
"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+=" Apache-2.0 MIT Unicode-DFS-2016"
SLOT="0"
KEYWORDS="~amd64"
